/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanly_thuvien;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class panel_quanlymuon extends javax.swing.JPanel {

    connect c = new connect();//khoi tao class connect để kết nối database
    private Connection conn;
    private DefaultTableModel dtm;

    public panel_quanlymuon() {
        initComponents();

        dtm = (DefaultTableModel) jTablephieuchomuon.getModel();
        dtm.setColumnIdentifiers(new Object[]{
            "Mã phiếu mượn", "Ngày mượn", "Ngày sẽ trả", "Mã độc giả", "Mã sách", "Số lượng mượn"
        });
        
        
        btnXoaphieuchomuon.setEnabled(false);
        hienthidata_combobox();
        hienthidata();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablephieuchomuon = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMaphieumuon = new javax.swing.JTextField();
        btnThemphieuchomuon = new javax.swing.JButton();
        btnSuaphieuchomuon = new javax.swing.JButton();
        btnXoaphieuchomuon = new javax.swing.JButton();
        btnCapnhatphieuchomuon = new javax.swing.JButton();
        txtngaymuon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtngaysetra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsoluongmuon = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        jPanel3.setPreferredSize(new java.awt.Dimension(930, 520));

        jTablephieuchomuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablephieuchomuon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTablephieuchomuonFocusLost(evt);
            }
        });
        jTablephieuchomuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablephieuchomuonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablephieuchomuon);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2), "Tìm kiếm vị trí sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/search.png"))); // NOI18N
        jButton4.setText("Tìm kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2), "Phiếu cho mượn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel8.setMaximumSize(new java.awt.Dimension(483, 259));
        jPanel8.setMinimumSize(new java.awt.Dimension(483, 259));

        jLabel10.setText("Mã phiếu mượn");

        jLabel11.setText("Ngày mượn");

        txtMaphieumuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaphieumuonMouseClicked(evt);
            }
        });
        txtMaphieumuon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaphieumuonKeyPressed(evt);
            }
        });

        btnThemphieuchomuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/add.png"))); // NOI18N
        btnThemphieuchomuon.setText("Cho mượn");
        btnThemphieuchomuon.setPreferredSize(new java.awt.Dimension(90, 32));
        btnThemphieuchomuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemphieuchomuonActionPerformed(evt);
            }
        });

        btnSuaphieuchomuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/edit.png"))); // NOI18N
        btnSuaphieuchomuon.setText("Sửa");
        btnSuaphieuchomuon.setPreferredSize(new java.awt.Dimension(90, 32));
        btnSuaphieuchomuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaphieuchomuonActionPerformed(evt);
            }
        });

        btnXoaphieuchomuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/delete.png"))); // NOI18N
        btnXoaphieuchomuon.setText("Trả");
        btnXoaphieuchomuon.setPreferredSize(new java.awt.Dimension(90, 32));
        btnXoaphieuchomuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaphieuchomuonActionPerformed(evt);
            }
        });

        btnCapnhatphieuchomuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/restart.png"))); // NOI18N
        btnCapnhatphieuchomuon.setText("Cập nhât");
        btnCapnhatphieuchomuon.setPreferredSize(new java.awt.Dimension(90, 32));
        btnCapnhatphieuchomuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatphieuchomuonActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày sẽ trả");

        jLabel1.setText("Mã sách");

        jLabel3.setText("Số lượng mượn");

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Mã độc giả");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaphieumuon, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtngaymuon, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtngaysetra)
                            .addComponent(txtsoluongmuon)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnThemphieuchomuon, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnSuaphieuchomuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnXoaphieuchomuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnCapnhatphieuchomuon, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtMaphieumuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtngaysetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsoluongmuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemphieuchomuon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaphieuchomuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaphieuchomuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapnhatphieuchomuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.getAccessibleContext().setAccessibleName("Tìm kiếm phiếu mượn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTablephieuchomuonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTablephieuchomuonFocusLost
        btnThemphieuchomuon.setEnabled(true);
    }//GEN-LAST:event_jTablephieuchomuonFocusLost

    private void jTablephieuchomuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablephieuchomuonMouseClicked
        btnThemphieuchomuon.setEnabled(false);
         btnXoaphieuchomuon.setEnabled(true);
        String ma = maRowSelected();

        ResultSet rs = c.loadData("select * from muon where maphieumuon=" + ma);

        //xoa de gan lai gia tri ứng với csdl
        cleardata_combobox();
        try {
            if (rs.next()) {
                txtMaphieumuon.setText(String.valueOf(rs.getInt(1)));

                txtngaymuon.setText(rs.getString(2));
                txtngaysetra.setText(rs.getString(3));

                jComboBox2.addItem(rs.getInt(4) + "");
                jComboBox1.addItem(rs.getInt(5) + "");
                txtsoluongmuon.setText(rs.getString(6));

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi click vào table");
        }
    }//GEN-LAST:event_jTablephieuchomuonMouseClicked

    private void txtMaphieumuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaphieumuonMouseClicked

    }//GEN-LAST:event_txtMaphieumuonMouseClicked

    private void txtMaphieumuonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaphieumuonKeyPressed

        btnThemphieuchomuon.setEnabled(true);
    }//GEN-LAST:event_txtMaphieumuonKeyPressed

    private void btnThemphieuchomuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemphieuchomuonActionPerformed

        int Mamoi = Integer.parseInt(txtMaphieumuon.getText());

        String ngaymuon = txtngaymuon.getText();
        String ngaysetra = txtngaysetra.getText();

        int masach = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        int madocgia = Integer.parseInt(jComboBox2.getSelectedItem().toString());

        int soluongmuon = Integer.parseInt(txtsoluongmuon.getText());

        String sql = String.format("INSERT INTO dbo.muon(maphieumuon,ngaymuon,ngayhuatra,masinhvien ,masach,soluongmuon )VALUES  (%d,CAST('%s' AS DATE),CAST('%s' AS DATE),%d,%d,%d)", Mamoi, ngaymuon, ngaysetra, madocgia, masach, soluongmuon);

        try {

            //kiểm tra số lượng mượn có được cho phép mượn ko?
            ResultSet rs1 = c.loadData("select soluong from sach where masach=" + masach);

            while (rs1.next()) {
                int soluongsach = rs1.getInt(1);

                if (soluongsach < soluongmuon) {
                    JOptionPane.showMessageDialog(this, "Số lượng mượn không được lớn hơn số lượng sách còn");
                } else {
                    c.insert_remove_updateData(sql);//thực hiện thêm

                    JOptionPane.showMessageDialog(this, "Thêm thành công");

                    int dk = 0;
                    int sl = 0;
                    ResultSet rs = c.loadData("SELECT masach,soluongmuon FROM dbo.muon WHERE masach IN (SELECT masach FROM dbo.muon)");

                    while (rs.next()) {
                        dk = rs.getInt(1);
                        sl = rs.getInt(2);

                    }
                    String sql1 = String.format("UPDATE dbo.sach SET sach.soluong=sach.soluong-%d  WHERE masach=%d ", sl, dk);
                    c.insert_remove_updateData(sql1);
                    System.out.println(dk + " " + sl);

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại !" + e);
        }
    }//GEN-LAST:event_btnThemphieuchomuonActionPerformed

    private void btnSuaphieuchomuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaphieuchomuonActionPerformed

        String ma = maRowSelected();

        //ep kieu
        int makiemtra = Integer.parseInt(ma);

        int Mamoi = Integer.parseInt(txtMaphieumuon.getText());
        int soluongmuon = Integer.parseInt(txtsoluongmuon.getText());
        String ngaymuon = txtngaymuon.getText();
        String ngaysetra = txtngaysetra.getText();

        int masach = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        int madocgia = Integer.parseInt(jComboBox2.getSelectedItem().toString());

        String sql = String.format("update muon set maphieumuon=%d,ngaymuon=CAST('%s' AS DATE),ngayhuatra=CAST('%s' AS DATE),masinhvien=%s,masach=%s,soluongmuon=%d where maphieumuon=%d", Mamoi, ngaymuon, ngaysetra, madocgia, masach, soluongmuon, makiemtra);

        
             //kiểm tra số lượng mượn có được cho phép mượn ko?
            ResultSet rs1 = c.loadData("select soluong from sach where masach=" + masach);

            try {
                while (rs1.next()) {
                    int soluongsach = rs1.getInt(1);
                    
                    if (soluongsach < soluongmuon) {
                        JOptionPane.showMessageDialog(this, "Số lượng mượn không được lớn hơn số lượng sách còn");
                    } else {
                        c.insert_remove_updateData(sql);
                        JOptionPane.showMessageDialog(this, "Sửa thành công");
                    }
                }   } catch (SQLException ex) {
                Logger.getLogger(panel_quanlymuon.class.getName()).log(Level.SEVERE, null, ex);
            }
catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sửa thất bại !" + e);
        }
    }//GEN-LAST:event_btnSuaphieuchomuonActionPerformed

    private void btnXoaphieuchomuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaphieuchomuonActionPerformed
        int dk = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        int sl = Integer.parseInt(txtsoluongmuon.getText());
        String ma = maRowSelected();

        //ep kieu
        int makiemtra = Integer.parseInt(ma);

        try {

            if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không ?") == 0) {
                c.insert_remove_updateData("delete from muon where maphieumuon=" + ma);
                JOptionPane.showMessageDialog(this, "Xóa thành công");

            }

            String sql1 = String.format("UPDATE dbo.sach SET sach.soluong=sach.soluong+%d  WHERE masach=%d ", sl, dk);
            c.insert_remove_updateData(sql1);
            System.out.println(dk + " " + sl);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa thất bại" + e);
        }
    }//GEN-LAST:event_btnXoaphieuchomuonActionPerformed

    private void btnCapnhatphieuchomuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatphieuchomuonActionPerformed

        //reset null tất cả
        txtMaphieumuon.setText("");
        txtngaymuon.setText("");
        txtsoluongmuon.setText("");
        txtngaysetra.setText("");
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();

        clearDataInTable();
        hienthidata();
    }//GEN-LAST:event_btnCapnhatphieuchomuonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        hienthidata_combobox();
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     clearDataInTable();
        try {
            String gttimkiem=txtTimkiem.getText();
            
            String sql="select * from muon where  maphieumuon like '%"+gttimkiem+"%'";
            ResultSet rs=c.loadData(sql);
            
            while(rs.next()){
                
                dtm.addRow(new Object[]{
                    rs.getInt(1), rs.getDate(2), rs.getDate(3), rs.getInt(4), rs.getInt(5), rs.getInt(6)
                });
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(panel_quanlysach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    public void cleardata_combobox() {
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();

    }

    public void hienthidata_combobox() {
        cleardata_combobox();
        try {
            ResultSet rs1 = c.loadData("SELECT masach FROM dbo.sach");

            while (rs1.next()) {
                //gan du lieu truy van duoc vao combo box
                jComboBox1.addItem(rs1.getInt(1) + ""); //ép kiểu số thành chuỗi chỉ cần +""
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            ResultSet rs1 = c.loadData("SELECT masinhvien FROM dbo.sinhvien ");

            while (rs1.next()) {
                //gan du lieu truy van duoc vao combo box
                jComboBox2.addItem(rs1.getInt(1) + ""); //ép kiểu số thành chuỗi chỉ cần +""
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void clearDataInTable() {
        for (int i = dtm.getRowCount() - 1; i >= 0; --i) {
            dtm.removeRow(i);
        }
    }

    public void setNullAll() {
        txtMaphieumuon.setText("");
        txtngaymuon.setText("");
        txtngaysetra.setText("");
        txtsoluongmuon.setText("");
    }

    public String maRowSelected() {
        int row = jTablephieuchomuon.getSelectedRow();
        String ma = this.jTablephieuchomuon.getModel().getValueAt(row, 0).toString();

        return ma;
    }

    public void hienthidata() {
        try {
            ResultSet rs = c.loadData("select * from muon");

            while (rs.next()) {
                dtm.addRow(new Object[]{
                    rs.getInt(1), rs.getDate(2), rs.getDate(3), rs.getInt(4), rs.getInt(5), rs.getInt(6)
                });

            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "Không có dữ liệu để hiển thị");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhatphieuchomuon;
    private javax.swing.JButton btnSuaphieuchomuon;
    private javax.swing.JButton btnThemphieuchomuon;
    private javax.swing.JButton btnXoaphieuchomuon;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablephieuchomuon;
    private javax.swing.JTextField txtMaphieumuon;
    private javax.swing.JTextField txtTimkiem;
    private javax.swing.JTextField txtngaymuon;
    private javax.swing.JTextField txtngaysetra;
    private javax.swing.JTextField txtsoluongmuon;
    // End of variables declaration//GEN-END:variables
}
