/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanly_thuvien;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class panel_quanlyloaisach extends javax.swing.JPanel {

     connect c=new connect();//khoi tao class connect để kết nối database
     private Connection conn;
    private DefaultTableModel dtm;
    public panel_quanlyloaisach() {
        initComponents();
            
        dtm=(DefaultTableModel) jTableloaisach.getModel();
        dtm.setColumnIdentifiers(new Object[]{
        
       "Mã loại sách","Tên loại sách"
    });
        btnThemloaisach.setEnabled(false);
        hienthidata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableloaisach = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMaloaisach = new javax.swing.JTextField();
        txtTenloaisach = new javax.swing.JTextField();
        btnThemloaisach = new javax.swing.JButton();
        btnSualoaisach = new javax.swing.JButton();
        btnXoaloaisach = new javax.swing.JButton();
        btnCapnhatloaisach = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(950, 665));

        jPanel2.setPreferredSize(new java.awt.Dimension(930, 520));

        jTableloaisach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableloaisach.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableloaisachFocusLost(evt);
            }
        });
        jTableloaisach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableloaisachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableloaisach);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0), 2), "Tìm kiếm loại sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 255, 0))); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/search.png"))); // NOI18N
        jButton4.setText("Tìm kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 2), "Chỉnh sửa loại sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 255, 51))); // NOI18N
        jPanel8.setMaximumSize(new java.awt.Dimension(483, 259));
        jPanel8.setMinimumSize(new java.awt.Dimension(483, 259));

        jLabel10.setText("Mã loại sách");

        jLabel11.setText("Tên loại sách");

        txtMaloaisach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaloaisachMouseClicked(evt);
            }
        });
        txtMaloaisach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaloaisachKeyPressed(evt);
            }
        });

        btnThemloaisach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/add.png"))); // NOI18N
        btnThemloaisach.setText("Thêm");
        btnThemloaisach.setPreferredSize(new java.awt.Dimension(90, 32));
        btnThemloaisach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemloaisachActionPerformed(evt);
            }
        });

        btnSualoaisach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/edit.png"))); // NOI18N
        btnSualoaisach.setText("Sửa");
        btnSualoaisach.setPreferredSize(new java.awt.Dimension(90, 32));
        btnSualoaisach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSualoaisachActionPerformed(evt);
            }
        });

        btnXoaloaisach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/delete.png"))); // NOI18N
        btnXoaloaisach.setText("Xóa");
        btnXoaloaisach.setPreferredSize(new java.awt.Dimension(90, 32));
        btnXoaloaisach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaloaisachActionPerformed(evt);
            }
        });

        btnCapnhatloaisach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/restart.png"))); // NOI18N
        btnCapnhatloaisach.setText("Cập nhât");
        btnCapnhatloaisach.setPreferredSize(new java.awt.Dimension(90, 32));
        btnCapnhatloaisach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatloaisachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnThemloaisach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnSualoaisach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(35, 35, 35)
                        .addComponent(txtMaloaisach, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnXoaloaisach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnCapnhatloaisach, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtTenloaisach, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtTenloaisach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaloaisach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemloaisach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSualoaisach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaloaisach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapnhatloaisach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableloaisachFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableloaisachFocusLost

    }//GEN-LAST:event_jTableloaisachFocusLost

    private void jTableloaisachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableloaisachMouseClicked
        btnThemloaisach.setEnabled(false);

        String ma=maRowSelected();

        ResultSet rs=c.loadData("select * from loaisach where maloaisach="+ma);

        //xoa de gan lai gia tri ứng với csdl

        try {
            if(rs.next()){
                txtMaloaisach.setText(String.valueOf(rs.getInt(1)));
                txtTenloaisach.setText(rs.getString(2));

            }} catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi click vào table");
            }
    }//GEN-LAST:event_jTableloaisachMouseClicked

    private void txtMaloaisachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaloaisachMouseClicked

    }//GEN-LAST:event_txtMaloaisachMouseClicked

    private void txtMaloaisachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaloaisachKeyPressed

        btnThemloaisach.setEnabled(true);

    }//GEN-LAST:event_txtMaloaisachKeyPressed

    private void btnThemloaisachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemloaisachActionPerformed

        int ma = Integer.parseInt(txtMaloaisach.getText());
        String ten = txtTenloaisach.getText();

        String sql=String.format("insert into loaisach(maloaisach,tenloaisach) values(%d,N'%s')",ma,ten);
        try{

            c.insert_remove_updateData(sql);//thực hiện thêm

            JOptionPane.showMessageDialog(this, "Thêm thành công");

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Thêm thất bại !"+e);
        }
    }//GEN-LAST:event_btnThemloaisachActionPerformed

    private void btnSualoaisachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSualoaisachActionPerformed

        String ma=maRowSelected();

        //ep kieu
        int makiemtra=Integer.parseInt(ma);

        int Mamoi = Integer.parseInt(txtMaloaisach.getText());
        String Tenmoi = txtTenloaisach.getText();

        String sql=String.format("update loaisach set maloaisach=%d,tenloaisach=N'%s' where maloaisach=%d",Mamoi,Tenmoi,makiemtra );

        try{
            c.insert_remove_updateData(sql);
            JOptionPane.showMessageDialog(this, "Sửa thành công");

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Sửa thất bại !"+e);
        }
    }//GEN-LAST:event_btnSualoaisachActionPerformed

    private void btnXoaloaisachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaloaisachActionPerformed
        try{

            String ma=maRowSelected();
            if(JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không ?")==0){
                c.insert_remove_updateData("delete from loaisach where maloaisach="+ma);
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            }

        }  catch(Exception e){
            JOptionPane.showMessageDialog(this, "Xóa thất bại" +e);
        }
    }//GEN-LAST:event_btnXoaloaisachActionPerformed

    private void btnCapnhatloaisachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatloaisachActionPerformed

        //reset null tất cả
        txtMaloaisach.setText("");
        txtTenloaisach.setText("");

        clearDataInTable();
        hienthidata();
    }//GEN-LAST:event_btnCapnhatloaisachActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      clearDataInTable();
        try {
            String gttimkiem=txtTimkiem.getText();
            
            String sql="select * from loaisach where tenloaisach like N'%"+gttimkiem+"%' or maloaisach like '%"+gttimkiem+"%'";
            ResultSet rs=c.loadData(sql);
            
            while(rs.next()){
                
                dtm.addRow(new Object[]{
                    rs.getInt(1),rs.getString(2)
                });
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(panel_quanlysach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
     public void hienthidata(){
       try {
                ResultSet rs=c.loadData("select * from loaisach");
             
            while(rs.next()){
                dtm.addRow(new Object[]{
                   rs.getInt(1),rs.getString(2)
                });
                
            }
           
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this, "Không có dữ liệu để hiển thị");
        }
    }
    public void clearDataInTable(){
        for(int i=dtm.getRowCount()-1;i>=0;--i){
            dtm.removeRow(i);
        }
    }  
    public String maRowSelected(){
        
        
         int row=jTableloaisach.getSelectedRow();
         String ma=this.jTableloaisach.getModel().getValueAt(row, 0).toString();
         
         return ma;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhatloaisach;
    private javax.swing.JButton btnSualoaisach;
    private javax.swing.JButton btnThemloaisach;
    private javax.swing.JButton btnXoaloaisach;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableloaisach;
    private javax.swing.JTextField txtMaloaisach;
    private javax.swing.JTextField txtTenloaisach;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
