/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class panel_quanlysach extends javax.swing.JPanel {

    connect c=new connect();//khoi tao class connect để kết nối database
     private Connection conn;
    private DefaultTableModel dtm;
    public panel_quanlysach() {
        initComponents();
        
        
       
     
       //setup gia tri mat dinh cac cot cho table 
        dtm=(DefaultTableModel) jTable1.getModel();
        dtm.setColumnIdentifiers(new Object[]{
        
       "Mã sách","Tên sách","Năm xuất bản","Số lượng","Mã NXB","Mã loại sách","Mã tác giả","Mã vị trí"
    });
        
        
        hienthidata_combobox();
        hienthidata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMasach = new javax.swing.JTextField();
        txtTensach = new javax.swing.JTextField();
        txtNamxuatban = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        btnThemsach = new javax.swing.JButton();
        btnSuasach = new javax.swing.JButton();
        btnXoasach = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnCapnhatsach = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(950, 530));

        jPanel1.setPreferredSize(new java.awt.Dimension(930, 520));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2), "Tìm kiếm sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 153, 204))); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/search.png"))); // NOI18N
        jButton4.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2), "Chỉnh sửa sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel8.setMaximumSize(new java.awt.Dimension(483, 259));
        jPanel8.setMinimumSize(new java.awt.Dimension(483, 259));

        jLabel10.setText("Mã sách");

        jLabel11.setText("Tên sách");

        jLabel12.setText("Năm xuất bản");

        jLabel13.setText("Số lượng");

        txtMasach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMasachMouseClicked(evt);
            }
        });
        txtMasach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMasachKeyPressed(evt);
            }
        });

        btnThemsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/add.png"))); // NOI18N
        btnThemsach.setText("Thêm");
        btnThemsach.setPreferredSize(new java.awt.Dimension(90, 32));
        btnThemsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemsachActionPerformed(evt);
            }
        });

        btnSuasach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/edit.png"))); // NOI18N
        btnSuasach.setText("Sửa");
        btnSuasach.setPreferredSize(new java.awt.Dimension(90, 32));
        btnSuasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuasachActionPerformed(evt);
            }
        });

        btnXoasach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/delete.png"))); // NOI18N
        btnXoasach.setText("Xóa");
        btnXoasach.setPreferredSize(new java.awt.Dimension(90, 32));
        btnXoasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoasachActionPerformed(evt);
            }
        });

        jLabel14.setText("Mã NXB");

        jLabel15.setText("Mã loại sách");

        jLabel16.setText("Mã tác giả");

        jLabel17.setText("Mã vị trí");

        btnCapnhatsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly_thuvien/image/restart.png"))); // NOI18N
        btnCapnhatsach.setText("Cập nhât");
        btnCapnhatsach.setPreferredSize(new java.awt.Dimension(90, 32));
        btnCapnhatsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatsachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel10)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTensach, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMasach, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnThemsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnSuasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnXoasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(41, Short.MAX_VALUE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnCapnhatsach, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtTensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemsach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapnhatsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 952, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(11, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 9, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
        hienthidata_combobox();
    }//GEN-LAST:event_jTable1FocusLost

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        btnThemsach.setEnabled(false);

        String ma=maRowSelected();

        ResultSet rs=c.loadData("select * from sach where masach="+ma);

        //xoa de gan lai gia tri ứng với csdl
        cleardata_combobox();

        try {
            if(rs.next()){
                txtMasach.setText(String.valueOf(rs.getInt(1)));
                txtTensach.setText(rs.getString(2));
                txtNamxuatban.setText(String.valueOf(rs.getInt(3)));
                txtSoluong.setText(String.valueOf(rs.getInt(4)));

                jComboBox1.addItem(rs.getInt(5)+"");
                jComboBox2.addItem(rs.getInt(6)+"");
                jComboBox3.addItem(rs.getInt(7)+"");
                jComboBox4.addItem(rs.getInt(8)+"");
            }} catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi click vào table");
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtMasachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMasachMouseClicked

    }//GEN-LAST:event_txtMasachMouseClicked

    private void txtMasachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMasachKeyPressed

        btnThemsach.setEnabled(true);
        hienthidata_combobox();
    }//GEN-LAST:event_txtMasachKeyPressed

    private void btnThemsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemsachActionPerformed
        ktRong();
        int txtMa = Integer.parseInt(txtMasach.getText());
        String txtTenas = txtTensach.getText();
        int txtNam = Integer.parseInt(txtNamxuatban.getText());
        int txtSL = Integer.parseInt(txtSoluong.getText());

        int manxb = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        int maloai = Integer.parseInt(jComboBox2.getSelectedItem().toString());
        int matacgia = Integer.parseInt(jComboBox3.getSelectedItem().toString());
        int mavitri = Integer.parseInt(jComboBox4.getSelectedItem().toString());

        String sql=String.format("insert into sach(masach,tensach,namxuatban,soluong,manxb,maloaisach,matacgia,mavitri) values(%d,N'%s',%d,%d,%d,%d,%d,%d)", txtMa,txtTenas,txtNam,txtSL,manxb,maloai,matacgia,mavitri);

        try{

            c.insert_remove_updateData(sql);//thực hiện thêm

            JOptionPane.showMessageDialog(this, "Thêm thành công");

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Thêm thất bại !"+e);
        }
    }//GEN-LAST:event_btnThemsachActionPerformed

    private void btnSuasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuasachActionPerformed

        String ma=maRowSelected();

        //ep kieu
        int makiemtra=Integer.parseInt(ma);

        int txtMa = Integer.parseInt(txtMasach.getText());
        String txtTen = txtTensach.getText();
        int txtNam = Integer.parseInt(txtNamxuatban.getText());
        int txtSL = Integer.parseInt(txtSoluong.getText());

        int manxb = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        int maloai = Integer.parseInt(jComboBox2.getSelectedItem().toString());
        int matacgia = Integer.parseInt(jComboBox3.getSelectedItem().toString());
        int mavitri = Integer.parseInt(jComboBox4.getSelectedItem().toString());

        String sql=String.format("update sach set masach=%d,tensach=N'%s',namxuatban=%d,soluong=%d,manxb=%d,maloaisach=%d,matacgia=%d,mavitri=%d where masach=%d",txtMa,txtTen,txtNam,txtSL,manxb,maloai,matacgia,mavitri,makiemtra );

        try{
            c.insert_remove_updateData(sql);
            JOptionPane.showMessageDialog(this, "Sửa thành công");

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Sửa thất bại !"+e);
        }
    }//GEN-LAST:event_btnSuasachActionPerformed

    private void btnXoasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoasachActionPerformed
        try{

            String ma=maRowSelected();
            if(JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không ?")==0){
                c.insert_remove_updateData("delete from sach where masach="+ma);
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            }

        }  catch(Exception e){
            JOptionPane.showMessageDialog(this, "Xóa thất bại" +e);
        }
    }//GEN-LAST:event_btnXoasachActionPerformed

    private void btnCapnhatsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatsachActionPerformed

        setNullAll();

        clearDataInTable();
        hienthidata();
    }//GEN-LAST:event_btnCapnhatsachActionPerformed
    public void ktRong(){
        if(this.txtMasach.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã sách");
            txtMasach.requestFocus(); //con trỏ focus ở txtMasach
            
        }
        else if(this.txtTensach.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên sách");
            txtTensach.requestFocus();
        }
        else if(this.txtNamxuatban.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập năm xuất bản");
            txtNamxuatban.requestFocus();
        }
        else if(this.txtSoluong.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số lượng");
            txtSoluong.requestFocus();
        }
       
        
    }    
    public void clearDataInTable(){
        for(int i=dtm.getRowCount()-1;i>=0;--i){
            dtm.removeRow(i);
        }
    }    public void setNullAll(){
        txtMasach.setText("");
        txtTensach.setText("");
        txtNamxuatban.setText("");
        txtSoluong.setText("");
    }    public String maRowSelected(){
         int row=jTable1.getSelectedRow();
         String ma=this.jTable1.getModel().getValueAt(row, 0).toString();
         
         return ma;
    }
    public void hienthidata_combobox(){
        cleardata_combobox();
        try{
                ResultSet rs1=c.loadData("SELECT manxb FROM dbo.nxb ");
                
                while(rs1.next()){
                    //gan du lieu truy van duoc vao combo box
                    jComboBox1.addItem(rs1.getInt(1)+""); //ép kiểu số thành chuỗi chỉ cần +""
                }     
            
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
                ResultSet rs1=c.loadData("SELECT maloaisach FROM dbo.loaisach ");
                
                while(rs1.next()){
                    //gan du lieu truy van duoc vao combo box
                    jComboBox2.addItem(rs1.getInt(1)+""); //ép kiểu số thành chuỗi chỉ cần +""
                }     
            
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
                ResultSet rs1=c.loadData("SELECT matacgia FROM dbo.tacgia ");
                
                while(rs1.next()){
                    //gan du lieu truy van duoc vao combo box
                    jComboBox3.addItem(rs1.getInt(1)+""); //ép kiểu số thành chuỗi chỉ cần +""
                }     
            
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
                ResultSet rs1=c.loadData("SELECT mavitri FROM dbo.vitrisach ");
                
                while(rs1.next()){
                    //gan du lieu truy van duoc vao combo box
                    jComboBox4.addItem(rs1.getInt(1)+""); //ép kiểu số thành chuỗi chỉ cần +""
                }     
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    public void cleardata_combobox(){
         jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
        jComboBox4.removeAllItems();
    }
    public void hienthidata(){
       try {
                ResultSet rs=c.loadData("select * from sach");
             
            while(rs.next()){
                dtm.addRow(new Object[]{
                   rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getInt(4),rs.getInt(5),rs.getInt(6),rs.getInt(7),rs.getInt(8)
                });
                
            }
           
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this, "Không có dữ liệu để hiển thị");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhatsach;
    private javax.swing.JButton btnSuasach;
    private javax.swing.JButton btnThemsach;
    private javax.swing.JButton btnXoasach;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txtMasach;
    private javax.swing.JTextField txtNamxuatban;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTensach;
    // End of variables declaration//GEN-END:variables
}
